from django.db import models

# Create your models here.

# cnn_model_api/utils.py
import os
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model

# Define image dimensions
img_height, img_width = 64, 64

# Class names (update if different)
class_names = ['s', 'm', 'q', 'n', 'f', 'v']

# Class descriptions
class_descriptions = {
    'f': 'Fusion of ventricular and normal beat', # Example: You might want to rename this to "Fusion Beat" in React
    'n': 'Normal', # Match this with a "Normal" entry in your heartConditions or handle it separately
    'm': 'Morphological variations',
    'q': 'Unclassifiable',
    's': 'Supraventricular premature beat', # Example: This should match the key in heartConditions
    'v': 'Premature ventricular contraction' # Example: This should match the key in heartConditions
}

# Load the model once when the Django app starts
_model = None

def load_ecg_model():
    global _model
    if _model is None:
        # Construct the absolute path to the model file
        # Assuming your model is in cnn_model_api/models/ecg_model.h5
        model_path = os.path.join(os.path.dirname(__file__), 'models', 'ecg_model.h5')
        try:
            _model = load_model(model_path)
            print(f"Model loaded successfully from: {model_path}")
        except Exception as e:
            print(f"Error loading model from {model_path}: {str(e)}")
            _model = None # Ensure it's None if loading fails
    return _model


def predict_ecg_image(image_file, confidence_threshold=0.7):
    model = load_ecg_model()
    if model is None:
        return "Error: Model not loaded", 0.0, None # Added None for condition

    try:
        # Read image from InMemoryUploadedFile
        img_np = np.frombuffer(image_file.read(), np.uint8)
        img = cv2.imdecode(img_np, cv2.IMREAD_COLOR)

        if img is None:
            return "Error: Invalid image file", 0.0, None

        # Resize and preprocess
        img = cv2.resize(img, (img_height, img_width))
        img = img / 255.0
        img = np.expand_dims(img, axis=0)

        # Make prediction
        predictions = model.predict(img, verbose=0)[0]
        max_confidence = np.max(predictions)
        predicted_class_index = np.argmax(predictions)

        # Check confidence threshold
        if max_confidence < confidence_threshold:
            return "uncertain", max_confidence, "Unclassified" # Returning "uncertain" status and condition "Unclassified"

        # Return prediction
        predicted_class_key = class_names[predicted_class_index]
        predicted_condition_name = class_descriptions.get(predicted_class_key, 'Unknown Condition')
        if predicted_class_key == 'n':
            status_result = "normal"
        elif predicted_class_key == 'q':
            status_result = "uncertain"
        else:
            status_result = "abnormal"

        return status_result, max_confidence, predicted_condition_name

    except Exception as e:
        return f"Error: {str(e)}", 0.0, None


# cnn_model_api/utils.py
import os
import smtplib
from email.message import EmailMessage
import logging
from django.conf import settings # Import Django settings
from django.core.mail import send_mail # Django's built-in email sender
from datetime import datetime # Make sure datetime is imported at the top


logger = logging.getLogger(__name__)

def send_email_report(to_email: str, result: dict) -> bool:
    """Send ECG report email safely using Django SMTP backend."""

    if not settings.CUSTOM_EMAIL_ENABLED:
        logger.warning("Email sending disabled (CUSTOM_EMAIL_ENABLED=False)")
        return False

    try:
        status_text = result.get('status', 'N/A')
        confidence_value = float(result.get('confidence', 0))
        confidence_text = f"{confidence_value * 100:.2f}%"

        condition_text = result.get('condition', 'Not specified')
        description_text = result.get('description', '')

        text_content = f"""
ECG Analysis Report

Status: {status_text}
Confidence: {confidence_text}
Condition: {condition_text}
Description: {description_text}

This is an automated ECG analysis report.
Please consult a medical professional for diagnosis.
"""

        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <h2 style="color:#2563eb;">ECG Analysis Report</h2>
            <p><strong>Status:</strong> {status_text}</p>
            <p><strong>Confidence:</strong> {confidence_text}</p>
            <p><strong>Condition:</strong> {condition_text}</p>
            <p><strong>Description:</strong> {description_text}</p>
            <hr>
            <p style="font-size:12px;color:#666;">
                This is an automated report generated by AI.
                It is not a substitute for professional medical advice.
            </p>
            <p style="font-size:12px;color:#666;">
                © {datetime.now().year} ECG Project
            </p>
        </body>
        </html>
        """

        send_mail(
            subject=f"ECG Report: {condition_text}",
            message=text_content,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[to_email],
            html_message=html_content,
            fail_silently=False,
        )

        logger.info(f"ECG report email sent to {to_email}")
        return True

    except Exception as e:
        logger.error(f"Email sending failed: {e}", exc_info=True)
        return False
